using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace AnonymousComplaintsAPI.Helpers;

/// <summary>
/// Attribute to require an external service permission on an endpoint.
/// The permission is checked against the JWT role claims of the caller's service token.
/// 
/// Usage: [RequireExternalPermission("tl-ext-read-users")]
/// 
/// This follows the same pattern as AccessGate's ExternalController:
/// - The calling application authenticates with a service token (JWT) generated by AccessGate
/// - The service token carries tl-ext-* permissions in the "role" claims
/// - This filter reads those claims and checks if the required permission is present
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true)]
public class RequireExternalPermissionAttribute : TypeFilterAttribute
{
    public RequireExternalPermissionAttribute(string permission)
        : base(typeof(ExternalServicePermissionFilter))
    {
        Arguments = new object[] { permission };
    }
}

/// <summary>
/// Action filter that checks if the caller's service token contains the required tl-ext-* permission.
/// 
/// How it works:
/// 1. [Authorize] on the controller already validated the JWT signature and expiry
/// 2. This filter extracts the caller's identity (NameIdentifier or "Id" claim)
/// 3. Reads all "role" claims from the JWT (these are the permissions)
/// 4. Checks if the required permission is present (case-insensitive)
/// 5. Returns 403 Forbidden if the permission is missing
/// </summary>
public class ExternalServicePermissionFilter : IAsyncActionFilter
{
    private readonly string _permission;
    private readonly ILogger<ExternalServicePermissionFilter> _logger;

    public ExternalServicePermissionFilter(
        string permission,
        ILogger<ExternalServicePermissionFilter> logger)
    {
        _permission = permission;
        _logger = logger;
    }

    public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        var user = context.HttpContext.User;

        // 1. Extract caller identity from JWT claims
        //    Service tokens use NameIdentifier (= user_id), same as AccessGate's GetCallerId()
        var callerIdClaim = user.FindFirst(ClaimTypes.NameIdentifier)
                         ?? user.FindFirst("sub");

        if (callerIdClaim == null)
        {
            _logger.LogWarning("[External API] Permission check failed: cannot resolve caller identity for permission '{Permission}'", _permission);
            context.Result = new ObjectResult(new { error = "Cannot resolve caller identity from token" })
            {
                StatusCode = StatusCodes.Status401Unauthorized
            };
            return;
        }

        // 2. Read all role/permission claims from the JWT
        //    AccessGate puts permissions in ClaimTypes.Role claims
        var permissions = user.FindAll(ClaimTypes.Role)
            .Select(c => c.Value)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        // 3. Check if the required permission is present
        if (!permissions.Contains(_permission))
        {
            _logger.LogWarning(
                "[External API] Permission denied: caller={CallerId} does not have permission '{Permission}'. Available: [{Available}]",
                callerIdClaim.Value, _permission, string.Join(", ", permissions));

            context.Result = new ObjectResult(new
            {
                error = $"Access denied. Required permission: {_permission}",
                detail = "The service token does not carry the required permission. " +
                         "Ensure the permission is assigned in AccessGate and the service token has been regenerated."
            })
            {
                StatusCode = StatusCodes.Status403Forbidden
            };
            return;
        }

        _logger.LogDebug("[External API] Permission granted: caller={CallerId}, permission={Permission}", callerIdClaim.Value, _permission);
        await next();
    }
}
