// <auto-generated />
using System;
using AnonymousComplaintsAPI.Models.Entities;
 
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AnonymousComplaintsAPI.Data;

#nullable disable

namespace AnonymousComplaintsAPI.Migrations
{
    [DbContext(typeof(AnonymousComplaintsV002Context))]
    partial class AnonymousComplaintsV002ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", b =>
                {
                    b.Property<int>("AnonymousComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnonymousComplaintID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnonymousComplaintId"));

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FrequencyId")
                        .HasColumnType("int")
                        .HasColumnName("FrequencyID");

                    b.Property<int?>("FusionWithId")
                        .HasColumnType("int")
                        .HasColumnName("FusionWithID");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("AnonymousComplaintId")
                        .HasName("PK__Anonymou__54E7974A0BBB4943");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("FusionWithId");

                    b.HasIndex("TypeId");

                    b.ToTable("AnonymousComplaints");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttachmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int?>("AnonymousComplaintId")
                        .HasColumnType("int")
                        .HasColumnName("AnonymousComplaintID");

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttachmentId")
                        .HasName("PK__Attachme__442C64DE2E016E74");

                    b.HasIndex("AnonymousComplaintId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B51D3BA1B");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Frequency", b =>
                {
                    b.Property<int>("FrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FrequencyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyId"));

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FrequencyId")
                        .HasName("PK__Frequenc__592474B82B67A39E");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SolutionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolutionId"));

                    b.Property<int?>("AnonymousComplaintId")
                        .HasColumnType("int")
                        .HasColumnName("AnonymousComplaintID");

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.HasKey("SolutionId")
                        .HasName("PK__Solution__6B633AF077192C53");

                    b.HasIndex("AnonymousComplaintId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<bool?>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId")
                        .HasName("PK__Types__516F03959BE84BD0");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC14030537");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Defendant", b =>
                {
                    b.Property<int>("AnonymousComplaintId")
                        .HasColumnType("int")
                        .HasColumnName("AnonymousComplaintID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AnonymousComplaintId", "UserId")
                        .HasName("PK__Defendan__859F1B80B65EB45E");

                    b.HasIndex("UserId");

                    b.ToTable("Defendants", (string)null);
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.Category", "Category")
                        .WithMany("AnonymousComplaints")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_AnonymousComplaint_Category");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("AnonymousComplaints")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_AnonymousComplaint_CreatedBy");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.Frequency", "Frequency")
                        .WithMany("AnonymousComplaints")
                        .HasForeignKey("FrequencyId")
                        .HasConstraintName("FK_AnonymousComplaint_Frequency");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", "FusionWith")
                        .WithMany("InverseFusionWith")
                        .HasForeignKey("FusionWithId")
                        .HasConstraintName("FK_AnonymousComplaint_Fusion");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.Type", "Type")
                        .WithMany("AnonymousComplaints")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__Anonymous__TypeI__2739D489");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Frequency");

                    b.Navigation("FusionWith");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Attachment", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", "AnonymousComplaint")
                        .WithMany("Attachments")
                        .HasForeignKey("AnonymousComplaintId")
                        .HasConstraintName("FK_Attachments_AnonymousComplaint");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Attachments_CreatedBy");

                    b.Navigation("AnonymousComplaint");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Category", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("Categories")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Categories_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Frequency", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("Frequencies")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Frequencies_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Solution", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", "AnonymousComplaint")
                        .WithMany("Solutions")
                        .HasForeignKey("AnonymousComplaintId")
                        .HasConstraintName("FK_Solutions_AnonymousComplaint");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("Solutions")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Solutions_CreatedBy");

                    b.Navigation("AnonymousComplaint");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Type", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.Category", "Category")
                        .WithMany("Types")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Types__CategoryI__151B244E");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", "CreatedByNavigation")
                        .WithMany("Types")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Types_CreatedBy");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Defendant", b =>
                {
                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", null)
                        .WithMany()
                        .HasForeignKey("AnonymousComplaintId")
                        .IsRequired()
                        .HasConstraintName("FK_Defendants_AnonymousComplaint");

                    b.HasOne("AnonymousComplaintsAPI.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Defendants_User");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.AnonymousComplaint", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("InverseFusionWith");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Category", b =>
                {
                    b.Navigation("AnonymousComplaints");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Frequency", b =>
                {
                    b.Navigation("AnonymousComplaints");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.Type", b =>
                {
                    b.Navigation("AnonymousComplaints");
                });

            modelBuilder.Entity("AnonymousComplaintsAPI.Models.Entities.User", b =>
                {
                    b.Navigation("AnonymousComplaints");

                    b.Navigation("Attachments");

                    b.Navigation("Categories");

                    b.Navigation("Frequencies");

                    b.Navigation("Solutions");

                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
